default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 123456
  port: 3306
  host: localhost

development:
  <<: *default
  database: Rails_Boilerplate_development

test:
  <<: *default
  database: Rails_Boilerplate_test

production:
  <<: *default
  database: Rails_Boilerplate_production
  username: Rails_Boilerplate
  password: <%= ENV["RAILS_BOILERPLATE_DATABASE_PASSWORD"] %>
